### ISSUE TITLE
Model for trx_parser is missing

### ISSUE THREAD

**Issue by orkenstein** [usc-sail/mica-screenplay-parser#1]
Hi and thanks for a great tool!

However trx_parser requires model:
https://github.com/usc-sail/mica-screenplay-parser/blob/6e18df8737ba3455a71132c31482ec07e2e7bfbb/screenplayparser/parser.py#L76

Which is not present in this repo. Am I missing something?

**Comment by sabyasachee** [comment]
Hello, sorry for the late response. I will add the model file soon and notify you here.

**Comment by orkenstein** [comment]
> Hello, sorry for the late response. I will add the model file soon and notify you here.

I trained it, no worries

**Comment by sabyasachee** [comment]
Model filed added in [latest commit](https://github.com/usc-sail/mica-screenplay-parser/commit/60ce59ea2f53df105029736dbfd96b5ad16fdc24)
